In [1]:
import numpy as np


# 1.Numpy

행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리

references: 
- [numpy](https://numpy.org/doc/stable/reference/index.html#reference)
- [cs231 numpy](https://cs231n.github.io/python-numpy-tutorial/)
- [Python For Data Science Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

<br>

numpy 특징 <br>
- 파이썬 리스트에 비해 빠르고, 메모리 효율적
- 반복문 없이 배열에 대한 처리 지원
- 다양한 기능 제공
<br>
<br>

numpy 기능 <br>
- 1. shape: numpy dimension
- 2. ndim: shape에서 얼마나 나오는지
- 3. dtype: numpy 원소의 데이터 타입

## 1.1 배열 생성

### 1.1.1 기본 배열 생성

#### arange
일정 범위의 배열을 생성 <br>
python의 range와 유사 <br>
단, arange는 실수 사용 가능 <br>

> 주의 <br>
np.arange(-3, 3, 0.5, dtype=int) <br>
array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

<br>

사용법
```python
x = np.arange(0, 10)
x = np.arange(-5, 5, 0.5)
```

In [2]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(0, 10, 0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [3]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [9]:
np.arange(0, 10) + 1  # 산술 연산 편리

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0, 10) * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.arange(0, 10) / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [12]:
(np.arange(0, 10) + 1) / (np.arange(0, 10) * 2)

C:\Users\user\AppData\Local\Temp\ipykernel_636\3470301314.py:1: RuntimeWarning: divide by zero encountered in true_divide
  (np.arange(0, 10) + 1) / (np.arange(0, 10) * 2)


array([       inf, 1.        , 0.75      , 0.66666667, 0.625     ,
       0.6       , 0.58333333, 0.57142857, 0.5625    , 0.55555556])

In [48]:
# sol 1

In [38]:
import random
# rank: 1~100등까지 등수가 담긴 array
# 1~20: 1, 21: 40, ...
ranks = np.random.choice(np.arange(1,101), size=100)
grades = []
for rank in ranks:
    if rank > 80:
        grades.append(5)
    elif rank > 60:
        grades.append(4)
    elif rank > 40:
        grades.append(3)
    elif rank > 20:
        grades.append(2)
    else:
        grades.append(1)

In [39]:
ranks

array([ 69,  13,   4,  28,  38,  65,  80,  96,  60,  31,  94,  29,  77,
        20,  45,  38,  23,  88,  33,  97,  83,  50,   9,  15,  92,  85,
        91,  99,   4,  82,  57,  85,  33,  36,  55,   7,  35,  57,  21,
         6,  48,  11,  47,  93,  62,   5,  59,  88,  23,  96,  33,  68,
        48,   9,   6,   6,  71,   4,  69,  49,  36,  25,  90,  91, 100,
        13,   8,  14, 100,  43,  67,  49,  57,   8,  14,  74,  95,  67,
        60,  60,  13,  58,  13,   4,  63,  53,  28,  80,  71,  44,  35,
        15,  70,  55,  62,  77,  11,  83,  69,  50])

In [40]:
grades

[4,
 1,
 1,
 2,
 2,
 4,
 4,
 5,
 3,
 2,
 5,
 2,
 4,
 1,
 3,
 2,
 2,
 5,
 2,
 5,
 5,
 3,
 1,
 1,
 5,
 5,
 5,
 5,
 1,
 5,
 3,
 5,
 2,
 2,
 3,
 1,
 2,
 3,
 2,
 1,
 3,
 1,
 3,
 5,
 4,
 1,
 3,
 5,
 2,
 5,
 2,
 4,
 3,
 1,
 1,
 1,
 4,
 1,
 4,
 3,
 2,
 2,
 5,
 5,
 5,
 1,
 1,
 1,
 5,
 3,
 4,
 3,
 3,
 1,
 1,
 4,
 5,
 4,
 3,
 3,
 1,
 3,
 1,
 1,
 4,
 3,
 2,
 4,
 4,
 3,
 2,
 1,
 4,
 3,
 4,
 4,
 1,
 5,
 4,
 3]

In [50]:
# sol 2

In [44]:
import random
# rank: 1~100등까지 등수가 담긴 array
# 1~20: 1, 21: 40, ...
ranks = np.random.choice(np.arange(1,101), size=100)
grades = []
for rank in ranks:
    if rank > 80:
        grades.append(5)
    elif rank > 60:
        grades.append(4)
    elif rank > 40:
        grades.append(3)
    elif rank > 20:
        grades.append(2)
    else:
        grades.append(1)
ranks.sort()
ranks[:20] = 1
ranks[20:40] = 2
ranks[40:60] = 3
ranks[60:80] = 4
ranks[80:100] = 5
ranks


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [51]:
# sol 3

In [ ]:
import random
# rank: 1~100등까지 등수가 담긴 array
# 1~20: 1, 21: 40, ...
ranks = np.random.choice(np.arange(1,101), size=100)
grades = []
for rank in ranks:
    if rank > 80:
        grades.append(5)
    elif rank > 60:
        grades.append(4)
    elif rank > 40:
        grades.append(3)
    elif rank > 20:
        grades.append(2)
    else:
        grades.append(1)

In [47]:
ranks = np.random.choice(np.arange(1,101), size=100)
((ranks-1) // 20) + 1

array([3, 3, 2, 1, 3, 3, 5, 1, 4, 1, 2, 2, 4, 1, 2, 1, 2, 5, 3, 2, 2, 3,
       2, 5, 2, 5, 3, 3, 5, 3, 2, 2, 5, 3, 4, 1, 5, 2, 4, 5, 5, 5, 2, 4,
       2, 3, 1, 5, 1, 3, 1, 1, 5, 5, 4, 1, 1, 4, 1, 1, 2, 1, 1, 4, 2, 5,
       2, 2, 4, 2, 5, 4, 5, 5, 2, 5, 4, 3, 2, 4, 3, 2, 4, 5, 1, 3, 2, 4,
       1, 3, 2, 2, 2, 1, 2, 3, 2, 1, 4, 3], dtype=int32)

In [54]:
np.array([[1,2,3], [4,5,6]], dtype=np.float32).shape

(2, 3)

In [55]:
np.array([[1,2,3], [4,5,6]], dtype=np.float32).ndim

2

#### linspace

arange와 유사 <br>
start와 stop를 주어진 숫자 만큼 분할

<br>

사용법
```python
x = np.linspace(2, 3, num=5)
x = np.linspace(2, 3, num=5, endpoint=False)    # 끝 점 미포함 
```

In [59]:
print(np.linspace(2, 3, num=5))  # 5개 값으로 분할
print(np.linspace(2, 3, num=5, endpoint=False))

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]


#### eye

대각행렬이 1이고 나머지가 0인 행렬 생성 <br>
k를 이용하여 1의 위치를 조정할 수 있음 <br>
<br>

사용법
```python
x = np.eye(10)    # np.identity와 동일
x = np.eye(10, k =1)
```

In [60]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [62]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
np.eye(5, k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

#### zeros

shape을 입력하면 모든 값이 0인 해당 shape에 맞는 배열 생성 <br>

사용법
```python
x = np.zeros(5)
x = np.zeros((5, 2), dtype=float)
```

In [70]:
print(np.zeros(5))
print("\n")
print(np.zeros((3,5,2)))

[0. 0. 0. 0. 0.]


[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


#### ones

shape을 입력하면 모든 값이 1인 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.ones(5)
x = np.ones((5, 2), dtype=float)
```

In [71]:
print(np.ones(5))
print("\n")
print(np.ones((3,5,2)))

[1. 1. 1. 1. 1.]


[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


#### full

shape과 숫자를 입력하면 입력한 숫자로 찬 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.full(5, np.inf)
x = np.full((5, 2), np.nan)
```

In [73]:
print(np.full(5, 3))
print("\n")
print(np.full((3,5,2), np.nan))

[3 3 3 3 3]


[[[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]]]


#### tril

lower triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
```

In [75]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

array([[ 1,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

In [77]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [79]:
print(np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 2))

[[0 0 3]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


#### triu

upper triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)
```

In [76]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

### 1.1.2 랜덤 배열 생성

#### random

균등분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.random(size=(2, 3))    # size: dim
```

In [81]:
np.random.random(size=(2,3))  # 0~1 사이의 난수 생성

array([[0.30390932, 0.07827255, 0.18117823],
       [0.69026196, 0.68384862, 0.44552517]])

#### randint

지정한 범위 내에서 임의의 수 생성

사용법
```python
x = np.random.randint(0, 10, size=(5,2))    # size: dim
```

In [88]:
np.random.randint(0, 10, size=(5, 2))

array([[4, 2],
       [7, 7],
       [2, 0],
       [5, 2],
       [7, 8]])

In [100]:
import numpy
import random

def success(money):
    lotto_count = money / 1000
    win_lotto_num = np.array([6, 14, 15, 19, 21, 41])
    for i in range(lotto_count):
        lotto_num = np.random.randint(1, 46, size=6)

    if (win_lotto_num == lotto_num):
        print("Win")
    

SyntaxError: invalid syntax (2873716715.py, line 14)

In [104]:
import tqdm
def lotto(money, win_numbers):
    np.random.randint(0, 10, size=(money//1000, 6))
    win_count = 0

    for number in tqdm(numbers):
        number.sort()

        if list(number) == win_numbers:
            win_count += 1

    return win_count

# print(lotto(100000000000, [10, 20, 55, 11, 14, 21]))
 

#### normal

정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.normal(loc=0, scale=1, size=(2, 3))
# loc: 평균
# scale: 분산
# size: dim
```

In [107]:
import random
np.random.normal(loc=0, scale=1, size=(5,2))

array([[ 1.4379063 , -1.840096  ],
       [ 1.04662671, -1.82804457],
       [-0.91770486, -0.59768601],
       [-0.81861028, -1.71261198],
       [ 1.08383443,  0.81234724]])

#### randn

표준정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.randn(2, 3)
```

In [109]:
np.random.randn(2, 3, 4)

array([[[-1.04974764, -0.56051273,  0.1417538 , -0.63278301],
        [ 2.92190464,  0.03679109, -0.13269274,  0.59802619],
        [-0.93658271, -1.15630484,  0.77829391, -0.55925526]],

       [[-0.64419372, -0.97322985,  1.00166263, -1.38265533],
        [-0.85542437,  1.29239261, -1.13113771, -0.03021988],
        [-1.59553423, -0.36276126,  0.15020903,  0.26432018]]])

## 1.2 배열 조작

### 1.2.1 배열 결합

#### concatenate

두 배열을 결합 <br>
<br>

사용법 
```python
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)
```

In [112]:
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)

In [113]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [114]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [115]:
np.concatenate([a,b], axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### 1.2.2 배열 분할

#### array_split

주어진 배열을 분할 <br>
<br>

사용법
```python
x = np.arange(9.0)
np.split(x, 3)
np.split(x, [3, 5, 6, 10])
```

In [122]:
x = np.arange(9)
print(np.split(x, 3))
print(np.split(x, [3,5,6,10]))  # 중요

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8]), array([], dtype=int32)]


### 1.2.3 차원 변경

#### reshape

배열의 모양을 원하는 형태로 바꿈 <br>
단, 바꾸는 배열의 차원 곱은 원 배열의 차원 곱과 일치해야 함 <br>
<br>

사용법
```python
x = np.arange(30)
x.reshape(5, 6)
```


In [123]:
np.arange(30).reshape(1, 30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

#### flatten

배열을 1차원 배열로 바꿈 <br>
<br>
사용법 <br>
```python
x = np.arange(30).reshape(2, 5, 3)
x.flatten()
```

In [124]:
np.arange(30).reshape(3, 2, 5).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### squeeze

불필요한 차원을 제거 <br>
즉, 길이가 0인 차원을 제거 <br>
<br>

사용법
```python
x = np.arange(10).reshape(10, 1, 1)
x.squeeze()
```

In [128]:
np.arange(30).reshape(1, 1, 1, 1, 30)

array([[[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
           15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]]]])

In [129]:
np.arange(30).reshape(1, 1, 1, 1, 30).squeeze()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### expand_dims

차원 추가 <br>
<br>

사용법
```python
x = np.arange(10)
np.expand_dims(x, 0)
```

In [132]:
x = np.arange(10)
np.expand_dims(x, 0)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 1.2.4 모양 변경

##### roll

배열을 입력한 수 만큼 이동 <br>
<br>

사용법
```python
x = np.arange(10)
np.roll(x, 2)
```

```python
x = np.reshape(x, (2, 5))
np.roll(x, 1)
np.roll(x, -1, axis=0)
np.roll(x, -1, axis=1)
```

In [135]:
x = np.arange(10)
print(np.roll(x, 2))
print(np.roll(x, -2))

[8 9 0 1 2 3 4 5 6 7]
[2 3 4 5 6 7 8 9 0 1]


In [138]:
x = np.arange(10).reshape(2, 5)
print(x)
print(np.roll(x, 1, axis=0))
print(np.roll(x, 1, axis=1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[5 6 7 8 9]
 [0 1 2 3 4]]
[[4 0 1 2 3]
 [9 5 6 7 8]]


##### flip

지정된 축을 기준으로 배열을 뒤집음 <br>
<br>

사용법

```python
x = np.arange(10).reshape(5, 2)
np.flip(x, 0)
```


In [144]:
x = np.arange(20).reshape(4, 5)
print(x)
print("-------")
print(np.flip(x, axis=0))
print("-------")
print(np.flip(x, axis=1))
print("-------")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-------
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
-------
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
-------


In [145]:
x.shape

(4, 5)

In [147]:
x[::-1,:]

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [149]:
x[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

### 1.2.5 축 변경

#### swapaxes

두 축의 위치를 지정하여 변경 <br>
<br>

사용법
```python
x = np.arange(100).reshape(5, 2, 10)
x.swapaxis(0, 2)    # 0 <-> 2
```

#### transpose

여러 축의 위치를 변경 <br>
transpose에 들어가는 인자는 축의 순서 <br>
<br>

사용법

```python
x = np.arange(100).reshape(5, 2, 10)
x.transpose(0, 2, 1)    # 1번 축과 2번 축을 바꿈
x.transpose(2, 0, 1)    # 2->0, 0->1, 1->2
```

### 1.2.6 배열 정렬

#### sort

주어진 축을 기준으로 배열 정렬 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.sort(axis=1)
x
```



In [152]:
# 원본 데이터가 바뀜
np.random.seed(1)
x = np.random.randint(0, 10, (5,4))
print(x)
print("----------")
x.sort(axis=0)
print(x)
print("----------")
x.sort(axis=1)
print(x)
print("----------")

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]
 [5 2 4 2]
 [4 7 7 9]]
----------
[[0 0 1 2]
 [4 2 2 4]
 [5 7 4 5]
 [5 8 7 7]
 [6 9 9 9]]
----------
[[0 0 1 2]
 [2 2 4 4]
 [4 5 5 7]
 [5 7 7 8]
 [6 9 9 9]]
----------


#### argsort

주어진 축을 기준으로 정렬된 배열의 인덱스 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.argsort(axis=1)
```


In [154]:
x = np.random.randint(0, 10, 10)
print(x)
print(x.argsort())

[0 1 8 8 3 9 8 7 3 6]
[0 1 4 8 9 7 2 3 6 5]


### 1.2.7 기타

##### unique

배열 내의 중복값 제거 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
np.unique(x, axis=0)
```

In [155]:
x = np.random.randint(0, 10, (5,2))
print(x)
print(np.unique(x))

[[5 1]
 [9 3]
 [4 8]
 [1 4]
 [0 3]]
[0 1 3 4 5 8 9]


In [160]:
x = np.full((2,3), np.nan)
np.nan_to_num(x, nan=-1)

array([[-1., -1., -1.],
       [-1., -1., -1.]])

In [161]:
np.nan_to_num((np.array([1,2,3]) / np.array([0,1,2])), nan=-1)

C:\Users\user\AppData\Local\Temp\ipykernel_636\634355631.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.nan_to_num((np.array([1,2,3]) / np.array([0,1,2])), nan=-1)


array([1.79769313e+308, 2.00000000e+000, 1.50000000e+000])

#### nan_to_num

배열 내의 nan 값을 특정 숫자로 변환 <br>
<br>

사용법
```python
x = np.full((3, 4), np.nan)
np.nan_to_num(x, nan=1)


#### trim_zeros

배열 내의 0값을 제거 <br>
<br>

사용법
```python
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trip_zeros(x, trip='f')    # 앞의 0만 제거
np.trip_zeros(x, trip='b')    # 뒤의 0만 제거
np.trip_zeros(x, trip='fb')   # 앞뒤 0 제거
```

In [168]:

x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
print(np.trim_zeros(x, trip='f'))
print(np.trim_zeros(x, trip='b'))   
print(np.trim_zeros(x, trip='fb'))  

TypeError: _trim_zeros() got an unexpected keyword argument 'trip'

stride_tricks

배열을 주어진 윈도우 만큼 분할 <br>
<br>

사용법
```python
x = np.arange(10)
y = np.lib.stride_tricks.sliding_window_view(x, 3)
```

In [171]:
x = np.arange(10)
print(
    np.lib.stride_tricks.sliding_window_view(x, 3)
)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [172]:
x = np.arange(10)
print(
    np.lib.stride_tricks.sliding_window_view(x, 5)
)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


In [173]:
np.lib.stride_tricks.sliding_window_view(x, 5).sum(axis=1)

array([10, 15, 20, 25, 30, 35])

## 1.3 배열 탐색

### argmax

축을 기준으로 배열에서 최댓값의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmax(x)
np.argmax(x, axis=0)
```

In [175]:
x = np.random.randint(0, 10, size=(2,3))
print(x)
print('-----------')
print(np.argmax(x))
print('-----------')
print(np.argmax(x, axis=0))
print('-----------')
print(np.argmax(x, axis=1))

[[7 7 9]
 [8 6 9]]
-----------
2
-----------
[1 0 0]
-----------
[2 2]


### argmin

축을 기준으로 배열에서 최솟걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmin(x)
np.argmin(x, axis=0)
```



In [178]:
x = np.random.randint(0, 10, size=(2,3))
print(x)
print('-----------')
print(np.argmin(x))
print('-----------')
print(np.argmin(x, axis=0))
print('-----------')
print(np.argmin(x, axis=1))
print('-----------')
print(np.argmin(x, axis=-1))

[[7 9 7]
 [3 0 8]]
-----------
4
-----------
[1 1 0]
-----------
[0 1]
-----------
[0 1]


### where

특정 조건에 맞는 값의 index 반환 또는 값 변환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.where(x < 5)    # 조건을 만족하는 값의 인덱스 반환
np.where(x < 5, 1, 0)    # x가 5보다 작은 값은 1, 그렇지 않으면 0
```

In [184]:
x[x <5]

array([3, 4, 2, 3, 3, 1, 3])

In [186]:
x = np.random.randint(1, 10, 10)
print(x)
print(x[np.where(x < 5)])
print(np.where(x<5, 1, 0))
print(x[np.where(x < 5,1,-1)])

[7 1 7 6 2 3 2 6 5 1]
[1 2 3 2 1]
[0 1 0 0 1 1 1 0 0 1]
[1 1 1 1 1 1 1 1 1 1]


### extract

특정 조건에 맞는 값을 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.extract(x > 2, x)
```

In [189]:
x = np.random.randint(1, 10, 10)
print(x)
print(x[np.extract(x > 5,x)])

[8 9 6 8 1 4 2 5 5 7]
[5 7 2 5 5]


##  1.4 배열 연산

### matmul

행렬 곱 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

np.matmul(x, y)
x @ y
```

In [193]:
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

print(x)
print(y)
print(np.matmul(x, y))
print(x @ y)

[[2 4]
 [3 0]]
[[6 0]
 [7 2]]
[[40  8]
 [18  0]]
[[40  8]
 [18  0]]


### eigen

eigenvalue, eigenvector 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.eig(x)
```



In [195]:
x = np.random.randint(0, 10, size=(2,2))
np.linalg.eig(x)

(array([ 6.69041576, -2.69041576]),
 array([[ 0.59659412, -0.28641169],
        [ 0.80254312,  0.95810665]]))

### det

배열의 행렬식을 구함 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.det(x)
```

In [196]:
x = np.random.randint(0, 10, size=(2,2))
print(x)
print(np.linalg.det(x))

[[3 8]
 [1 4]]
4.000000000000001


### trace
대각원소의 합 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.trace(x)
```

In [199]:
x = np.random.randint(0, 10, size=(2,2))
print(x)
np.trace(x)

[[3 5]
 [3 2]]


5

### solve

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
#  x_0 + 2*x_1 = 1
# 3x_0 + 5*x_1 = 2:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)
```

In [204]:
a = np.array([[1,2], [3,5]])
b = np.array([1,2])
np.linalg.solve(a, b)

array([-1.,  1.])

inv

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.inv(x)
```

In [200]:
x = np.random.randint(0, 10, size=(2,2))
print(x)
np.linalg.inv(x)

[[4 4]
 [0 3]]


array([[ 0.25      , -0.33333333],
       [ 0.        ,  0.33333333]])

## 1.5 통계 함수

#### ptp

축별 최댓값 - 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.ptp(axis=0)
```

In [206]:
x = np.arange(12).reshape(4,3)
print(x)
print('---------')
print(x.ptp(axis=0))
print('---------')
print(x.ptp(axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
---------
[9 9 9]
---------
[2 2 2 2]


#### median

축별 중앙값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
np.median(x, axis=0)
```

In [208]:
x = np.arange(12).reshape(4,3)
print(x)
print('---------')
print(np.median(x, axis=0))
print('---------')
print(np.median(x, axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
---------
[4.5 5.5 6.5]
---------
[ 1.  4.  7. 10.]


### sum

축별 합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
x.sum(axis=1)
```

In [210]:
x = np.arange(12).reshape(4,3)
print(x)
print('---------')
print(x.sum(axis=0))
print('---------')
print(x.sum(axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
---------
[18 22 26]
---------
[ 3 12 21 30]


### average

축별 가중합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
np.average(x, weights=[0.5, 0.3, 0.2])
```

In [211]:
x = np.array([3, 4, 5])
np.average(x, weights=[0.5,0.3,0.2])

3.7

### mean

축별 평균 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.mean(axis=1)
```

### min

축별 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.min(axis=1)
```

### max

축별 최댓값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.max(axis=1)
```

### std
축별 표준편차 산출 <br>
<br>

사용법

```python
x = np.arange(12).reshape(4,3)
x.std(axis=1)
```

### cov

공분산 산출 <br>
<br>

사용법
```python
x = np.random.rand(25).reshape(5, 5)
np.cov(x)
```